version: '3.3'

services:
   go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.go_app.loadbalancer.server.port=1773"
    networks:
      - wapi1net
