version: '3.8'
services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - ./dbdata:/app/dbdata
   - ./files:/app/files
  depends_on:
   - db
  command: ['-logtype', 'json']

 db:
  image: postgres:14-alpine
  ports:
   - ${POSTGRES_PORT}:${POSTGRES_PORT}
  volumes:
   - ~/apps/postgres:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_DB=${POSTGRES_DB}
