version: '3.8'
services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - ./dbdata:/app/dbdata
   - ./files:/app/files
  ports:
   - 8080:8080

 db:
  image: postgres:14-alpine
  ports:
   - ${DB_PORT}:${DB_PORT}
  volumes:
   - ~/apps/postgres:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=${DB_PASSWORD}
   - POSTGRES_USER=${DB_USER}
   - POSTGRES_DB=${DB_NAME}
  networks:
      - wapi1net
